-- Higher Education Alumni Targeting Demo - Database Setup
-- This script sets up the database, schema, and tables for the demo

-- Create database and schema
CREATE DATABASE IF NOT EXISTS HIGHER_ED_DEMO;
USE DATABASE HIGHER_ED_DEMO;
CREATE SCHEMA IF NOT EXISTS ALUMNI_TARGETING;
USE SCHEMA ALUMNI_TARGETING;

-- Create warehouse for demo (adjust size as needed)
CREATE WAREHOUSE IF NOT EXISTS HIGHER_ED_WH 
WITH WAREHOUSE_SIZE = 'SMALL' 
AUTO_SUSPEND = 60 
AUTO_RESUME = TRUE;

-- Use the warehouse
USE WAREHOUSE HIGHER_ED_WH;

-- Grant necessary privileges (adjust as needed for your environment)
GRANT USAGE ON DATABASE HIGHER_ED_DEMO TO ROLE PUBLIC;
GRANT USAGE ON SCHEMA ALUMNI_TARGETING TO ROLE PUBLIC;
GRANT SELECT ON ALL TABLES IN SCHEMA ALUMNI_TARGETING TO ROLE PUBLIC;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ALUMNI_TARGETING TO ROLE PUBLIC; 