-- Higher Education Alumni Targeting Demo - Table Creation
-- This script creates the tables for storing alumni and venue data

USE DATABASE HIGHER_ED_DEMO;
USE SCHEMA ALUMNI_TARGETING;

-- Create alumni donors table
CREATE OR REPLACE TABLE ALUMNI_DONORS (
    DONOR_ID VARCHAR(50) PRIMARY KEY,
    FIRST_NAME VARCHAR(100),
    LAST_NAME VARCHAR(100),
    FULL_NAME VARCHAR(200),
    EMAIL VARCHAR(200),
    ADDRESS_ID VARCHAR(50),  -- Links to marketplace US_ADDRESSES table
    STREET_ADDRESS VARCHAR(500),
    CITY VARCHAR(100),
    STATE VARCHAR(50),
    ZIP_CODE VARCHAR(10),
    LATITUDE FLOAT,
    LONGITUDE FLOAT,
    GRADUATION_YEAR INTEGER,
    DEGREE_TYPE VARCHAR(100),
    MAJOR VARCHAR(150),
    AGE INTEGER,
    ANNUAL_DONATION_AMOUNT DECIMAL(10,2),
    CUMULATIVE_DONATION_AMOUNT DECIMAL(12,2),
    LAST_DONATION_DATE DATE,
    DONOR_SEGMENT VARCHAR(50),  -- Major, Mid-level, Annual
    H3_LEVEL_7 VARCHAR(20),
    H3_LEVEL_8 VARCHAR(20),
    H3_LEVEL_9 VARCHAR(20),
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- Create event venues table
CREATE OR REPLACE TABLE EVENT_VENUES (
    VENUE_ID VARCHAR(50) PRIMARY KEY,
    VENUE_NAME VARCHAR(200),
    VENUE_TYPE VARCHAR(100),  -- Restaurant, Hotel, Event Center, etc.
    ADDRESS_ID VARCHAR(50),
    STREET_ADDRESS VARCHAR(500),
    CITY VARCHAR(100),
    STATE VARCHAR(50),
    ZIP_CODE VARCHAR(10),
    LATITUDE FLOAT,
    LONGITUDE FLOAT,
    CAPACITY INTEGER,
    PRICE_RANGE VARCHAR(20),  -- $, $$, $$$, $$$$
    RATING DECIMAL(3,2),
    PHONE VARCHAR(20),
    WEBSITE VARCHAR(300),
    DESCRIPTION VARCHAR(1000),
    H3_LEVEL_7 VARCHAR(20),
    H3_LEVEL_8 VARCHAR(20),
    H3_LEVEL_9 VARCHAR(20),
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- Create a summary table for quick analytics
CREATE OR REPLACE TABLE DONOR_ANALYTICS_SUMMARY (
    ZIP_CODE VARCHAR(10),
    H3_LEVEL_7 VARCHAR(20),
    H3_LEVEL_8 VARCHAR(20),
    H3_LEVEL_9 VARCHAR(20),
    DONOR_COUNT INTEGER,
    TOTAL_ANNUAL_DONATIONS DECIMAL(15,2),
    TOTAL_CUMULATIVE_DONATIONS DECIMAL(15,2),
    AVG_ANNUAL_DONATION DECIMAL(10,2),
    AVG_CUMULATIVE_DONATION DECIMAL(12,2),
    MAJOR_DONORS_COUNT INTEGER,  -- Donors giving $10K+ annually
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
); 